bind_addr = ":8080"
log_level = "debug"
log_path = "log/logrus.log"
database_url = "host=localhost port=15432 dbname=heagotest user=testgouser password=pgpwd4gotest sslmode=disable"
conf_token_path = "pkg/jwt/config.toml"